name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: xcodebuild -project swiftsky.xcodeproj build -configuration Release
      - name: Create DMG
        run: npm i -g create-dmg && create-dmg build/Release/swiftsky.app
        continue-on-error: true
      - uses: actions/upload-artifact@v3
        with:
          name: swiftsky
          path: swiftsky*.dmg
